Added exception handling and logging. Closes issue #381.
SubhrajitPrusty/codex-github pull request #131
Opened 2019-10-06 06:07 UTC by punndcoder28

2019-10-07 06:09 UTC, SubhrajitPrusty commented
Hey, thanks for the update.
I've seen you've added some specific exceptions only.
Can you add some generic exceptions on top of it? Because working with API calls, we don't know what kind of errors to except always.

2019-10-07 07:11 UTC, punndcoder28 commented
I could maybe add the base exception so that it is always called. Is this ok?

2019-10-07 07:24 UTC, SubhrajitPrusty commented
Sure, that will work.

2019-10-09 06:59 UTC, punndcoder28 commented
Hey @SubhrajitPrusty. Can you check the commit and let me know if any changes are needed.
Thanks.

2019-10-17 14:03 UTC, punndcoder28 commented
Are there any changes to be done @SubhrajitPrusty ? Please let me know.

2019-10-18 06:54 UTC, SubhrajitPrusty requested changes

2019-10-18 06:54 UTC, SubhrajitPrusty commented on update.py
> +except PyMongoError:
This will throw another exception because PyMongoError doesn't exist by default, i.e. you have to import it to use it.

You can do 

```
try:
    ---
except Exception as e:
    if type(e).__name__ == 'PyMongoError':
        print("whatever message")
    else:
        print("Unknown error", e)
```

instead.

or just import PyMongoError from the module

2019-10-18 06:54 UTC, SubhrajitPrusty commented on userdata.py
> +			print("User not found")
Again, this error message is not correct.
In case of an universal exception, we do not know what may have caused it.
So, it may be various reasons, rather than user not found.

2019-10-19 17:49 UTC, punndcoder28 commented
Hey. I've made the changes as requested.

2019-10-20 13:43 UTC, merged

2019-10-20 13:43 UTC, SubhrajitPrusty commented
Thanks