Added username
SubhrajitPrusty/codex-github pull request #19
Opened 2018-10-22 09:30 UTC by sachiket

2018-10-22 11:44 UTC, SubhrajitPrusty requested changes
See #17 

- [x] Invalid syntax
- [ ] Add name to README.md

2018-10-23 07:49 UTC, sachiket reviewed
Resolved

2018-10-23 11:34 UTC, SubhrajitPrusty commented
Update README.md in this branch only.

2018-10-23 21:00 UTC, SubhrajitPrusty approved these changes

2018-10-23 21:00 UTC, merged